- name: installing nginx
  apt:
    name: nginx

- name: adding www user to shared group
  user:
    name: '{{ www_user }}'
    append: yes
    groups:
      - '{{ shared_group }}'

- name: finding enabled sites
  find:
    paths: /etc/nginx/sites-enabled
    file_type: link
    excludes: '{{ freedns_main_domain.name }}'
  register: enabled_sites

- name: removing enabled sites
  file:
    path: '{{ item.path }}'
    state: absent
  with_items: '{{ enabled_sites.files }}'

- name: finding html files
  find:
    paths: '{{ www_web_root }}'
    file_type: file
  register: html_files

- name: removing html files
  file:
    path: '{{ item.path }}'
    state: absent
  with_items: '{{ html_files.files }}'

- name: copying index.html file
  copy:
    src: index.html
    dest: '{{ www_web_root }}'

- name: installing passlib for creating www web user
  pip:
    name: passlib

- name: creating www web user and password
  htpasswd:
    path: /etc/nginx/.htpasswd
    name: '{{ www_web_login_user }}'
    password: '{{ www_web_login_pass }}'
    mode: u=rw,g=r,o=

- name: creating site for
  template:
    src: site.j2
    dest: /etc/nginx/sites-available/{{ freedns_main_domain.name }}

- name: enabling site
  file:
    src: /etc/nginx/sites-available/{{ freedns_main_domain.name }}
    path: /etc/nginx/sites-enabled/{{ freedns_main_domain.name }}
    state: link

- name: making sure nginx is restarted
  service:
    name: nginx
    state: restarted

- name: checking if port 80 is open
  wait_for:
    host: '{{ item.name }}'
    port: 80
    timeout: 3
  with_items: '{{ freedns_domains }}'
