- name: installing nginx
  apt:
    name: nginx

- name: adding www user to shared group
  user:
    name: '{{ www_user }}'
    append: yes
    groups:
      - '{{ shared_group }}'

- name: finding enabled sites
  find:
    paths: /etc/nginx/sites-enabled
    file_type: link
    excludes: '{{ freedns_main_domain.name }}'
  register: enabled_sites

- name: removing enabled sites
  file:
    path: '{{ item.path }}'
    state: absent
  with_items: '{{ enabled_sites.files }}'

- name: making sure www web root exists and is accessible by shared group
  file:
    path: '{{ www_web_root }}'
    group: '{{ shared_group }}'
    state: directory

- name: making sure /var/log/nginx exists and nginx can access it
  file:
    path: /var/log/nginx
    owner: '{{ www_user }}'
    group: '{{ www_group }}'
    state: directory

- name: copying index.html file
  copy:
    src: index.html
    dest: '{{ www_web_root }}'

- name: installing pip in order to install passlib
  apt:
    name: python-pip

- name: installing passlib for creating www web user
  pip:
    name: passlib

- name: creating www web user and password
  htpasswd:
    path: /etc/nginx/.htpasswd
    name: '{{ www_web_login_user }}'
    password: '{{ www_web_login_pass }}'
    group: '{{ shared_group }}'
    mode: u=rw,g=r,o=

- name: creating site
  template:
    src: site.j2
    dest: /etc/nginx/sites-available/{{ freedns_main_domain.name }}

- name: enabling site
  file:
    src: /etc/nginx/sites-available/{{ freedns_main_domain.name }}
    path: /etc/nginx/sites-enabled/{{ freedns_main_domain.name }}
    state: link

- name: disabling nginx access and error logs
  lineinfile:
    path: /etc/nginx/nginx.conf
    firstmatch: yes
    regexp: "^\t{{ item }}_log .*{{ item }}\\.log;$"
    line: "\t{{ item }}_log off;"
  with_items:
    - access
    - error

- name: making sure nginx is restarted
  service:
    name: nginx
    state: restarted

- name: checking if port 80 is open
  wait_for:
    host: '{{ item.name }}'
    port: 80
    timeout: 3
  with_items: '{{ freedns_domains }}'
