- name: making sure php-fpm is available for nginx
  apt:
    name: php7.0-fpm

- name: creating php-fpm pool configuration for rutorrent
  template:
    src: pool.conf.j2
    dest: /etc/php/7.0/fpm/pool.d/rutorrent.conf

- name: making sure php-fpm is restarted
  service:
    name: php7.0-fpm
    state: restarted