- name: installing rtorrent
  apt:
    name: rtorrent

- name: creating rtorrent configuration
  template:
    src: .rtorrent.rc.j2
    dest: /home/{{ rtorrent_user }}/.rtorrent.rc
    owner: '{{ rtorrent_user }}'
    group: '{{ rtorrent_www_shared_group }}'

- name: creating rtorrent folder
  file:
    path: /home/{{ rtorrent_user }}/rtorrent
    owner: '{{ rtorrent_user }}'
    group: '{{ rtorrent_www_shared_group }}'
    state: directory

- name: creating folder for scgi sock
  file:
    path: /var/run/rtorrent
    owner: '{{ rtorrent_user }}'
    group: '{{ rtorrent_www_shared_group }}'
    state: directory

- name: creating rtorrent service
  template:
    src: rtorrent.service.j2
    dest: /etc/systemd/system/rtorrent.service

- name: making sure rtorrent is restarted
  service:
    name: rtorrent
    state: restarted

- name: checking if rtorrent's port is open 
  wait_for:
    host: '{{ freedns_main_domain.name }}'
    port: '{{ rtorrent_port }}'
    timeout: 3