- name: creating rtorrent user and adding to shared group
  user:
    name: '{{ rtorrent_user }}'
    group: '{{ shared_group }}'
    create_home: no

- name: making sure rtorrent directory is accessible to shared group
  file:
    path: '{{ rtorrent_dir }}'
    group: '{{ shared_group }}'
    state: directory

- name: installing rtorrent
  apt:
    name: rtorrent

- name: creating rtorrent configuration
  template:
    src: .rtorrent.rc.j2
    dest: '{{ rtorrent_dir }}/.rtorrent.rc'
    owner: '{{ rtorrent_user }}'
    group: '{{ shared_group }}'

- name: creating rtorrent folder
  file:
    path: '{{ rtorrent_dir }}'
    owner: '{{ rtorrent_user }}'
    group: '{{ shared_group }}'
    state: directory

- name: creating folder for scgi sock
  file:
    path: /var/run/rtorrent
    owner: '{{ rtorrent_user }}'
    group: '{{ shared_group }}'
    state: directory

- name: creating rtorrent service
  template:
    src: rtorrent.service.j2
    dest: /etc/systemd/system/rtorrent.service

- name: making sure rtorrent is restarted
  service:
    name: rtorrent
    state: restarted

- name: checking if rtorrent's port is open 
  wait_for:
    host: '{{ freedns_main_domain.name }}'
    port: '{{ rtorrent_port }}'
    timeout: 3