- name: creating rtorrent user and adding to shared group
  user:
    name: '{{ rtorrent_user }}'
    group: '{{ shared_group }}'
    create_home: no

- name: installing rtorrent
  apt:
    name: rtorrent

- name: installing atd and at for task scheduling
  apt:
    name: at

- name: creating rtorrent folder and making sure its accessible to shared group
  file:
    path: '{{ rtorrent_dir }}'
    owner: '{{ rtorrent_user }}'
    group: '{{ shared_group }}'
    state: directory

- name: creating rtorrent configuration
  template:
    src: .rtorrent.rc.j2
    dest: '{{ rtorrent_dir }}/.rtorrent.rc'
    owner: '{{ rtorrent_user }}'
    group: '{{ shared_group }}'

- name: adding move on completion rtorrent drop-in config
  template:
    src: move-on-completion.rc.j2
    dest: '{{ rtorrent_dir }}/config.d/move-on-completion.rc'
    owner: '{{ rtorrent_user }}'
    group: '{{ shared_group }}'

- name: adding completion path shell script
  template:
    src: get-completion-path.sh.j2
    dest: '{{ rtorrent_dir }}/get-completion-path.sh'
    owner: '{{ rtorrent_user }}'
    group: '{{ shared_group }}'
    mode: u+x

- name: installing pip3 for ffmpeg-transcode script
  apt:
    name: python3-pip
  tags: a

- name: installing jinja2 for ffmpeg-transcode script
  pip:
    executable: pip3
    name: jinja2
  tags: a

- name: copying ffmpeg-transcode script
  copy:
    src: ffmpeg-transcode.py
    dest: '{{ rtorrent_dir }}'
    owner: '{{ rtorrent_user }}'
    group: '{{ shared_group }}'
    mode: u+x
  tags: a

- name: creating folder for scgi sock
  file:
    path: /var/run/rtorrent
    owner: '{{ rtorrent_user }}'
    group: '{{ shared_group }}'
    state: directory

- name: creating rtorrent service
  template:
    src: rtorrent.service.j2
    dest: /etc/systemd/system/rtorrent.service

- name: making sure rtorrent is restarted
  service:
    name: rtorrent
    enabled: yes
    state: restarted

- name: checking if rtorrent's port is open
  wait_for:
    host: '{{ freedns_main_domain.name }}'
    port: '{{ rtorrent_port }}'
    timeout: 3
