- name: installing samba
  apt:
    name: samba

- name: creating samba config
  template:
    src: samba.conf.j2
    dest: /etc/samba/smb.conf

- name: restarting samba
  service:
    name: smbd
    state: restarted

- name: setting samba password for admin user
  shell: |
    smbpasswd -a {{ admin_user }}

    expect "New SMB password:"
    send "{{ admin_samba_pass }}\n"

    expect "\nRetype new SMB password:"
    send "{{ admin_samba_pass }}\n"

    exit 0
  args:
    executable: /usr/bin/expect