ansible_connection: '{{ vault_ansible_connection }}'
ansible_host: '{{ vault_ansible_host }}'
ansible_port: '{{ vault_ansible_port }}'
ansible_user: '{{ vault_ansible_user }}'
ansible_become: '{{ vault_ansible_become }}'
ansible_become_user: '{{ vault_ansible_become_user }}'
ansible_become_pass: '{{ vault_ansible_become_pass }}'
ansible_ssh_private_key_file: '{{ vault_ansible_ssh_private_key_file }}'

freedns_domains: '{{ vault_freedns_domains }}'
freedns_main_domain: '{{ vault_freedns_main_domain }}'