- name: installing rutorrent plugin dependencies
  apt:
    name:
      - unrar
      - ffmpeg
      - mediainfo
  tags: a

- name: cloning rutorrent repository
  git:
    repo: '{{ rutorrent_git_repo }}'
    dest: '{{ rutorrent_dir }}'
    version: '{{ rutorrent_git_version }}'
    force: yes

- name: creating rutorrent config.php
  template:
    src: config.php.j2
    dest: '{{ rutorrent_dir }}/conf/config.php'

- name: initializing plugins for rutorrent user before applying correct owner and group permissions
  command: php {{ rutorrent_dir }}/php/initplugins.php {{ www_web_login_user }}

- name: allowing access for www and shared group
  file:
    path: '{{ rutorrent_dir }}'
    owner: '{{ www_user }}'
    group: '{{ shared_group }}'
    mode: u=rwx,g=rwx,o=rx
    state: directory
    recurse: yes

- name: reloading nginx
  service:
    name: nginx
    state: reloaded