- name: installing passlib for creating rutorrent user
  pip:
    name: passlib

- name: creating rutorrent user and password for nginx
  htpasswd:
    path: /etc/nginx/.htpasswd
    name: '{{ rutorrent_login_user }}'
    password: '{{ rutorrent_login_pass }}'
    mode: u=rw,g=r,o=

- name: cloning rutorrent repository
  git:
    repo: '{{ rutorrent_git_repo }}'
    dest: '{{ rutorrent_dir }}'
    version: '{{ rutorrent_git_version }}'
    force: yes

- name: creating rutorrent config.php
  template:
    src: config.php.j2
    dest: '{{ rutorrent_dir }}/conf/config.php'

- name: initializing plugins for rutorrent user before applying correct owner and group permissions
  command: >
    php {{ rutorrent_dir }}/php/initplugins.php {{ rutorrent_login_user }}

- name: allowing access for rtorrent/www shared group
  file:
    path: '{{ rutorrent_dir }}'
    owner: '{{ www_user }}'
    group: '{{ rtorrent_www_shared_group }}'
    mode: u=rwx,g=rwx,o=rx
    state: directory
    recurse: yes

- name: reloading nginx
  service:
    name: nginx
    state: reloaded