- name: updating apt cache before start
  apt:
    update_cache: yes

- name: installing mosh
  apt:
    name: mosh

- name: installing tree
  apt:
    name: tree

- name: adding admin user to shared group
  user:
    name: '{{ admin_user }}'
    append: yes
    groups:
      - '{{ shared_group }}'

- name: making sure we're provisiong debian
  fail:
    msg: can provision debian only
  when: ansible_distribution != 'Debian'

- name: making sure we're provisiong stretch
  fail:
    msg: can provision stretch only
  when: ansible_distribution_release != 'stretch'

- name: making sure we're provisiong armv7
  fail:
    msg: can provision armv7 only
  when: ansible_architecture is not match('armv7.*')

- name: creating shared group
  group:
    name: '{{ shared_group }}'
    gid: '{{ shared_group_id }}'

- name: creating logrotate config for /tmp/*.log
  copy:
    src: tmp
    dest: /etc/logrotate.d/
  tags: a
