- name: making sure we're provisiong debian
  fail:
    msg: can provision debian only
  when: ansible_distribution != 'Debian'

- name: making sure we're provisiong stretch  
  fail:
    msg: can provision stretch only
  when: ansible_distribution_release != 'stretch'

- name: making sure we're provisiong armv7
  fail:
    msg: can provision armv7 only
  when: ansible_architecture is not match('armv7.*')

- name: creating mount point for storage device
  file:
    path: '{{ vault_storage_device_mount_point }}'
    group: '{{ torrent_group }}'
    state: directory

- name: mounting storage device by uuid to mount point
  mount:
    path: '{{ vault_storage_device_mount_point }}'
    src: UUID={{ vault_storage_device_uuid }}
    fstype: '{{ vault_storage_device_fstype }}'
    boot: yes
    state: mounted