letsencrypt_email: '{{ vault_letsencrypt_email }}'

shared_group: '{{ vault_shared_group }}'
shared_group_id: '{{ vault_shared_group_id }}'

plex_user: '{{ vault_plex_user }}'

rtorrent_user: '{{ vault_rtorrent_user }}'
rtorrent_port: '{{ vault_rtorrent_port }}'

www_user: '{{ vault_www_user }}'
www_web_root: '{{ vault_www_web_root }}'
www_web_login_user: '{{ vault_www_web_login_user }}'
www_web_login_pass: '{{ vault_www_web_login_pass }}'

rutorrent_dir: '{{ vault_rutorrent_dir }}'
rutorrent_git_repo: '{{ vault_rutorrent_git_repo }}'
rutorrent_git_version: '{{ vault_rutorrent_git_version }}'

storage_device_mount_point: '{{ vault_storage_device_mount_point }}'
storage_device_uuid: '{{ vault_storage_device_uuid }}'
storage_device_fstype: '{{ vault_storage_device_fstype }}'
storage_device_directories: '{{ vault_storage_device_directories }}'

syncthing_user: '{{ vault_syncthing_user }}'
syncthing_gui_host: '{{ vault_syncthing_gui_host }}'
syncthing_gui_port: '{{ vault_syncthing_gui_port }}'
syncthing_gui_user: '{{ vault_syncthing_gui_user }}'
syncthing_gui_pass: '{{ vault_syncthing_gui_pass }}'

tautulli_user: '{{ vault_tautulli_user }}'
tautulli_group: '{{ vault_tautulli_group }}'
tautulli_dir: '{{ vault_tautulli_dir }}'
tautulli_web_host: '{{ vault_tautulli_web_host }}'
tautulli_web_port: '{{ vault_tautulli_web_port }}'
tautulli_web_user: '{{ vault_tautulli_web_user }}'
tautulli_web_pass: '{{ vault_tautulli_web_pass }}'
tautulli_git_repo: '{{ vault_tautulli_git_repo }}'
tautulli_git_version: '{{ vault_tautulli_git_version }}'

esm_dir: '{{ vault_esm_dir }}'
esm_git_repo: '{{ vault_esm_git_repo }}'
esm_git_version: '{{ vault_esm_git_version }}'

mariadb_root_pass: '{{ vault_mariadb_root_pass }}'
mariadb_admin_user: '{{ vault_mariadb_admin_user }}'
mariadb_admin_pass: '{{ vault_mariadb_admin_pass }}'
mariadb_bind_address: '{{ vault_mariadb_bind_address }}'

admin_user: '{{ vault_admin_user }}'
admin_samba_pass: '{{ vault_admin_samba_pass }}'