- name: making sure we can use https with apt
  apt:
    name: apt-transport-https

- name: importing apt public key for plex
  apt_key:
    url: https://dev2day.de/pms/dev2day-pms.gpg.key

- name: adding apt sources list entry for plex
  apt_repository:
    repo: deb https://dev2day.de/pms/ stretch main
    filename: pms

- name: installing plex
  apt:
    update_cache: yes
    name: plexmediaserver-installer

- name: creating rtorrent/plex shared group
  group:
    name: '{{ rtorrent_plex_shared_group }}'

- name: adding plex user to rtorrent/plex shared group
  user:
    name: '{{ plex_user }}'
    append: yes
    groups:
      - '{{ rtorrent_plex_shared_group }}'

- name: making sure plex is started with the rtorrent/plex shared group
  lineinfile:
    path: /lib/systemd/system/plexmediaserver.service
    regexp: ^Group={{ plex_user }}
    line: Group={{ rtorrent_plex_shared_group }}

- name: restarting plex service
  service:
    name: plexmediaserver
    state: restarted