- name: making sure we can use https with apt
  apt:
    name: apt-transport-https

- name: importing apt public key for plex
  apt_key:
    url: https://dev2day.de/pms/dev2day-pms.gpg.key

- name: adding apt sources list entry for plex
  apt_repository:
    repo: deb https://dev2day.de/pms/ stretch main
    filename: pms

- name: installing plex
  apt:
    name: plexmediaserver-installer
    update_cache: yes

- name: adding plex user to storage shared group
  user:
    name: '{{ plex_user }}'
    append: yes
    groups:
      - '{{ shared_group }}'

- name: making sure plex is started under shared group permissions
  lineinfile:
    path: /lib/systemd/system/plexmediaserver.service
    regexp: ^Group=.*$
    line: Group={{ shared_group }}

- name: restarting plex service
  service:
    name: plexmediaserver
    state: restarted