- name: importing apt public key for syncthing
  apt_key:
    url: https://syncthing.net/release-key.txt

- name: adding apt sources list entry for syncthing
  apt_repository:
    repo: deb https://apt.syncthing.net/ syncthing stable
    filename: syncthing

- name: installing syncthing
  apt:
    name: syncthing
    update_cache: yes

- name: creating syncthing user
  user:
    name: syncthing
    group: '{{ shared_group }}'

- name: creating syncthing service
  template:
    src: syncthing.service.j2
    dest: /etc/systemd/system/syncthing.service

- name: installing lxml to satisfy ansible xml module dependency
  apt:
    name: python-lxml

- name: setting syncthing config parameter
  xml:
    path: /home/{{ syncthing_user }}/.config/syncthing/config.xml
    xpath: '{{ item.xpath }}'
    attribute: '{{ item.attribute }}'
    value: '{{ item.value }}'
  with_items:
    - xpath: /configuration/gui
      attribute: tls
      value: 'true'

- name: setting syncthing config parameters
  xml:
    path: /home/{{ syncthing_user }}/.config/syncthing/config.xml
    xpath: '{{ item.xpath }}'
    value: '{{ item.value }}'    
  with_items:
    - xpath: /configuration/gui/address
      value: '{{ syncthing_gui_host }}:{{ syncthing_gui_port }}'
    - xpath: /configuration/gui/user
      value: '{{ syncthing_gui_user }}'
    - xpath: /configuration/gui/password
      value: '{{ syncthing_gui_pass }}'

- name: making sure syncthing is restarted
  service:
    name: syncthing
    state: restarted